name: Manual

on:
  workflow_dispatch:
    inputs:
      utc_offset: {type: string, required: true, description: "UTC Offset", default: "-08:00"}

jobs:
  _dfa01139-d687-4c85-b685-3547bc346d9c:
    name: "manual job #1"
    uses: davidbrownell/test_repo/.github/workflows/callable.yaml
    with:
      utc_offset: ${{ inputs.utc_offset }}
