name: Periodic (Local Midnight)
run-name: "Local Midnight: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}"

on:
  schedule:
    - cron: '0 8 * * *' # 4pm UTC (12am local w/ -800)

jobs:
  _dfa01139-d687-4c85-b685-3547bc346d9c:
    name: "periodic hourly job #1"
    uses: davidbrownell/test_repo/.github/workflows/callable.yaml@latest
    with:
      utc_offset: "-08:00"
